### ISSUE TITLE
Enter Choice: 4 Error

### ISSUE THREAD

**Issue by farrasrayhand** [kmhmubin/Face-Recognition-Attendance-System#25]
********** WELCOME MENU **********
[1] Check Camera
[2] Capture Faces
[3] Train Images
[4] Recognize & Attendance
[5] Auto Mail
[6] Quit
Enter Choice: 4
[ERROR:0] VIDEOIO(DSHOW): raised unknown C++ exception!

Traceback (most recent call last):
  File ".\main.py", line 101, in <module>
    mainMenu()
  File ".\main.py", line 41, in mainMenu
    CaptureFaces()
  File ".\main.py", line 79, in CaptureFaces
    mainMenu()
  File ".\main.py", line 44, in mainMenu
    Trainimages()
  File ".\main.py", line 88, in Trainimages
    mainMenu()
  File ".\main.py", line 47, in mainMenu
    RecognizeFaces()
  File ".\main.py", line 95, in RecognizeFaces
    Recognize.recognize_attendence()
  File "C:\Users\Administrator\Downloads\Compressed\Face-Recognition-Attendance-System-master\FRAS\Recognize.py", line 30, in recognize_attendence
    gray = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by kmhmubin** [comment]
Please install OpenCV again or correctly.
