### ISSUE TITLE
Error Option 4

### ISSUE THREAD

**Issue by staticshreyas** [kmhmubin/Face-Recognition-Attendance-System#35]
********** WELCOME MENU **********
[1] Check Camera
[2] Capture Faces
[3] Train Images
[4] Recognize & Attendance
[5] Auto Mail
[6] Quit
Enter Choice: 4
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    mainMenu()
  File "main.py", line 47, in mainMenu
    RecognizeFaces()
  File "main.py", line 95, in RecognizeFaces
    Recognize.recognize_attendence()
  File "/Users/shreyasmore/Downloads/OpenSourceRepo/Face-Recognition-Attendance-System/FRAS/Recognize.py", line 30, in recognize_attendence
    gray = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.1) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-yvyj7qlp/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by ayush9198gupta** [comment]
@staticshreyas 

Do things in a list:
install/upgrade opencv/opencv-contrib package
create env and install the dependencies accordingly and rerun 
check your camera and recheck the images generated in TrainingImageLabel folder

This will solve your issue.
